# Site settings
title: 'Arahant' # Your Title
tagline: 'Ein Blog eines jungen Meditierenden' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: /strange_case # the subpath of your site, e.g. /blog/
